-- module Config
--     ( Config(..)
--     ) where
--
-- import Control.Monad.Reader (ReaderT)
--
-- import CliOptions (Options)
--
-- -- type Config = Options
--
-- -- data Config a = ReaderT Options a
-- -- newtype Config a = ReaderT Options
-- --     { config :: Options
--
-- newtype Config = Config
--     { 
